PATH_LOG: "log_bt.txt"
LOG_LEVEL: "DEBUG"

TEXT_COLUMN: "text"
LABEL_COLUMN: "labels"

INPUT_PATH: "Inputs/trainset.jsonl"
OUPTUT_PATH_DATA_AUG: "/Outputs/data_aug"
OUPTUT_PATH_MODEL: "/Outputs/model"
COLUMN_NAMES: 
- 'id'
- 'text'
- 'labels'
- 'Comments'

FROM_MODEL_NAME: "Helsinki-NLP/opus-mt-fr-en"
TO_MODEL_NAME: "Helsinki-NLP/opus-mt-en-fr"